### ISSUE TITLE
Code problem of paper "online next-best-view planner for 3D-exploration and inspection with a mobile manipulator robot"

### ISSUE THREAD

**Issue by zy-cuhk** [fkie/fkie-nbv-planner#1]
Hello, I am reading your paper of "online next-best-view planner for 3D-exploration and inspection with a mobile manipulator robot". Based on the link you leave in the above paper, I find this place is where you open your source code of your paper. However, I did not find any code here. Therefore, can you add your code since you have published your paper?

**Comment by francisc0garcia** [comment]
Hi, thanks for your interest! ... Yes, we are preparing the public version of our simulation environment, planner code and utilities. It should be ready soon.

**Comment by roehling** [comment]
The code is available now. Thank you for your patience!

**Comment by zy-cuhk** [comment]
Thank you very much !
